### ISSUE TITLE
👋 Link to xjtlu-lug

### ISSUE THREAD

**Issue by dexhunter** [awesome-xjtlu/wiki#2]
Greetings from a graduated student, I and other students have written something about SURF & ICS notes, maybe you would want to [have a look](https://github.com/xjtlu-lug). I can create a PR as well if you guys find suitable with your site.

**Comment by dexhunter** [comment]
We used to own short urls lik `xjt.lu` or `xjtlu.moe` but since most of the maintainers have graduated so the domains are no longer kept. But you guys can still purchase those if you like.

**Comment by chongfengling** [comment]
Nice work! Currently I can create a link to your repository and will put modified text by our maintainers soon. Thanks for your sharing.

**Comment by chongfengling** [comment]
Using a short url is in our long-term plan and we will consider your suggestions. 👍

**Comment by dexhunter** [comment]
sounds good to me
